version: "3.9"
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "54320:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
